"""Prodinamik Engine v1.1 — Scaffolding Generator

Generates new profile modules and project scaffolds.
Usage: `prodinamik new profile <name>` or `prodinamik new project <name>`
"""

import os
import sys
from pathlib import Path
from typing import Optional

# ──────────────────────────────────────────────
# Templates
# ──────────────────────────────────────────────

PROFILE_TEMPLATE = '''"""
Prodinamik Profile: {name}
Auto-generated by `prodinamik new profile {name}`
"""

from engine.profile import ProductProfile
from engine.state_machine import StateMachineParser


{name_camel}STATES_YAML = """
profile: {name}
name: {name}-profile
version: 1.0

states:
  backlog:
    type: initial
    max_reentries: null
    description: "Ideas waiting to be processed"

  active:
    type: intermediate
    max_reentries: 10
    timeout_seconds: 86400
    description: "Work in progress"

  review:
    type: intermediate
    max_reentries: 5
    timeout_seconds: 43200
    description: "Pending review"

  done:
    type: terminal
    max_reentries: 0
    description: "Completed successfully"

  cancelled:
    type: error
    max_reentries: 0
    description: "Abandoned or rejected"

transitions:
  backlog -> active:
    description: "Start working"
  active -> review:
    description: "Submit for review"
    condition: "work_complete"
  review -> active:
    description: "Revise after review"
    condition: "changes_requested"
  review -> done:
    description: "Mark complete"
    condition: "approved"
  review -> cancelled:
    description: "Abandon"
    condition: "rejected"
  active -> cancelled:
    description: "Abandon mid-work"
    condition: "abandoned"
"""


class {name_camel}Profile(ProductProfile):
    """Custom profile for {name} workflow."""

    name = "{name}"
    version = "1.0"
    description = "Auto-generated {name} profile"
    state_machine_yaml = {name_camel}STATES_YAML

    def __init__(self):
        super().__init__()
        self._initialized = False

    def initialize(self):
        self.state_machine = StateMachineParser.parse_string(self.state_machine_yaml)
        self._initialized = True

    @property
    def validators(self):
        return []

    @property
    def adapters(self):
        return []

    @property
    def budget(self):
        from engine.profile import Budget
        return Budget(soft_limit_usd=0.50, hard_limit_usd=1.0, hard_warn_frac=0.8)

    def __repr__(self):
        return f"<{{self.__class__.__name__}} name={{self.name}} v={{self.version}}>"
'''

PROJECT_TEMPLATE = '''"""
Prodinamik Project: {name}
"""

import sys
from pathlib import Path

# Ensure engine is importable
_here = Path(__file__).parent
if str(_here) not in sys.path:
    sys.path.insert(0, str(_here))

from engine.profile import ProductProfile
from engine.state_machine import StateMachineParser


# Profile
# ──────────────────────────────────────────────

PROFILE_YAML = """
profile: {name}
name: {name}
version: 1.0

states:
  todo:
    type: initial
    max_reentries: null
    description: "Queued items"

  doing:
    type: intermediate
    max_reentries: 10
    timeout_seconds: 86400
    description: "In progress"

  done:
    type: terminal
    max_reentries: 0
    description: "Completed"

transitions:
  todo -> doing:
    description: "Start item"
  doing -> done:
    description: "Complete item"
    condition: "verified"
"""


if __name__ == "__main__":
    from engine.config import ProdinamikConfig
    from engine.runtime import AsyncEngine

    cfg = ProdinamikConfig.load()
    engine = AsyncEngine(cfg)
    print(f"🚀 {name} project ready")
    print(f"   Engine: Prodinamik v1.1")
    print(f"   Run `prodinamik shell` to start")
'''

INIT_TEMPLATE = '''"""Prodinamik profiles"""
'''

README_TEMPLATE = """# {name}

Prodinamik Engine project — auto-generated.

## Quick Start

```bash
# Install
pip install -e .

# Interactive shell
prodinamik shell

# Create a run
prodinamik run {name} "my first task"

# List runs
prodinamik list

# Performance benchmarks
prodinamik benchmark
```

## Structure

```
├── profile.py           # Profile definition
├── prodinamik.yaml      # Engine configuration
└── runs/                # Run data (auto-created)
```
"""


# ──────────────────────────────────────────────
# Generator
# ──────────────────────────────────────────────

def generate_profile(name: str, output_dir: Path) -> Path:
    """Generate a new profile module"""
    output_dir.mkdir(parents=True, exist_ok=True)

    # CamelCase version of the name
    name_camel = "".join(word.capitalize() for word in name.replace("-", "_").split("_"))

    filepath = output_dir / f"{name}.py"
    if filepath.exists():
        raise FileExistsError(f"Profile already exists: {filepath}")

    content = PROFILE_TEMPLATE.format(name=name, name_camel=name_camel)
    filepath.write_text(content)

    # Create __init__.py if needed
    init_path = output_dir / "__init__.py"
    if not init_path.exists():
        init_path.write_text(INIT_TEMPLATE)

    return filepath


def generate_project(name: str, output_dir: Path) -> Path:
    """Generate a new project scaffold"""
    project_dir = output_dir / name
    if project_dir.exists():
        raise FileExistsError(f"Project directory already exists: {project_dir}")

    project_dir.mkdir(parents=True)

    # profile.py
    output = PROJECT_TEMPLATE.format(name=name)
    (project_dir / "profile.py").write_text(output)

    # prodinamik.yaml
    (project_dir / "prodinamik.yaml").write_text(
        f"""# Prodinamik Engine Configuration for {name}
data_dir: "./runs"
log:
  level: INFO
  format: text
runtime:
  poll_interval: 5
  health_check_interval: 60
  max_shutdown_wait: 10
  auto_recover: true
  enable_timeout_watcher: true
"""
    )

    # README
    (project_dir / "README.md").write_text(README_TEMPLATE.format(name=name))

    # .gitkeep for runs
    runs_dir = project_dir / "runs"
    runs_dir.mkdir(exist_ok=True)
    (runs_dir / ".gitkeep").write_text("")

    return project_dir


def list_profiles(profile_dir: Optional[Path] = None) -> list:
    """List available profile modules"""
    if profile_dir is None:
        from .cli import get_config
        cfg = get_config()
        profile_dir = Path(cfg.data_dir).parent / "profiles"

    if not profile_dir.exists():
        return []

    profiles = []
    for f in sorted(profile_dir.glob("*.py")):
        if f.name == "__init__.py":
            continue
        profiles.append(f.stem)
    return profiles
